from flask_restful import Resource, reqparse


class Search(Resource):
    # parser = reqparse.RequestParser()
    # parser.add_argument('t1',
    #                     type=str,
    #                     # required=True,
    #                     # help="This field cannot be blank."
    #                     )
    # parser.add_argument('t2',
    #                     type=int,
    #                     # required=True,
    #                     # help="This field cannot be blank."
    #                     )

    def get(self, criteria):

        if (criteria.lower() == "zugmodul"):
            return {
                "Zugmodul_MPa_trocken": {"min": 0, "max": 8},
                "Zugmodul_MPa_konditioniert": {"min": 0, "max": 10},
                "Zugmodul_Kriech_1h_MPa_trocken": {"min": 0, "max": 20},
                "Zugmodul_Kriech_1h_MPa_konditioniert": {"min": 0, "max": 12},
                "Zugmodul_Kriech_1000h_MPa_trocken": {"min": 0, "max": 16},
                "Zugmodul_Kriech_1000h_MPa_konditioniert": {"min": 0, "max": 14},
                "Zugmodul_Parallel_MPa_trocken": {"min": 0, "max": 15},
                "Zugmodul_Parallel_MPa_konditioniert": {"min": 0, "max": 13},
                "Zugmodul_Senkrecht_MPa_trocken": {"min": 0, "max": 17},
                "Zugmodul_Senkrecht_MPa_konditioniert": {"min": 0, "max": 9},
            }
        elif criteria.lower() == "bruchdehnung":
            return {
                "Bruchdehnung_trocken": {"min": 0, "max": 8},
                "Bruchdehnung_konditioniert": {"min": 0, "max": 10},
                "Bruchdehnung_Nominell_trocken": {"min": 0, "max": 20},
                "Bruchdehnung_Nominell_konditioniert": {"min": 0, "max": 12},
                "Bruchdehnung_TPE_trocken": {"min": 0, "max": 16},
                "Bruchdehnung_TPE_konditioniert": {"min": 0, "max": 14},
                "Bruchdehnung_Parallel_trocken": {"min": 0, "max": 15},
                "Bruchdehnung_Parallel_konditioniert": {"min": 0, "max": 13},
            }
        else:  # placeholder for now
            return {
                "Zugmodul_MPa_trocken": {"min": 0, "max": 8},
                "Zugmodul_MPa_konditioniert": {"min": 0, "max": 10},
                "Zugmodul_Kriech_1h_MPa_trocken": {"min": 0, "max": 20},
                "Zugmodul_Kriech_1h_MPa_konditioniert": {"min": 0, "max": 12},
                "Zugmodul_Kriech_1000h_MPa_trocken": {"min": 0, "max": 16},
                "Zugmodul_Kriech_1000h_MPa_konditioniert": {"min": 0, "max": 14},
                "Zugmodul_Parallel_MPa_trocken": {"min": 0, "max": 15},
                "Zugmodul_Parallel_MPa_konditioniert": {"min": 0, "max": 13},
                "Zugmodul_Senkrecht_MPa_trocken": {"min": 0, "max": 17},
                "Zugmodul_Senkrecht_MPa_konditioniert": {"min": 0, "max": 9},
            }


class Results(Resource):

    # parser.add_argument('t1',
    #                     type=str,
    #                     # required=True,
    #                     # help="This field cannot be blank."
    #                     )
    # parser.add_argument('t2',
    #                     type=str
    #                     # required=True,
    #                     # help="This field cannot be blank."
    #
    # )

    parser = reqparse.RequestParser()

    parser.add_argument("id", type=int)
    parser.add_argument("mat_desc", type=str)
    parser.add_argument("mat_int_desc", type=str)
    parser.add_argument("t_fam_id", type=str)
    parser.add_argument("campus_fam", type=str)
    parser.add_argument("t_mara_art_id", type=str)
    parser.add_argument("upload_kind", type=str)
    parser.add_argument("created_at", type=str)
    parser.add_argument("updated_at", type=str)
    parser.add_argument("unit", type=str)
    parser.add_argument("del_kz", type=str)
    parser.add_argument("producer", type=str)
    parser.add_argument("Verarbeitungsmethode", type=str)
    parser.add_argument("dichte_trocken", type=str)
    parser.add_argument("dichte_konditioniert", type=str)
    parser.add_argument("Belastung_trocken", type=str)
    parser.add_argument("Belastung_konditioniert", type=str)
    parser.add_argument("Temperatur_trocken", type=str)
    parser.add_argument("Temperatur_konditioniert", type=str)
    parser.add_argument("MVR_trocken", type=str)
    parser.add_argument("MVR_konditioniert", type=str)
    parser.add_argument("Bruchdehnung_trocken", type=str)
    parser.add_argument("Bruchdehnung_konditioniert", type=str)
    parser.add_argument("Bruchdehnung_Nominell_trocken", type=str)
    parser.add_argument("Bruchdehnung_Nominell_konditioniert", type=str)
    parser.add_argument("Bruchdehnung_TPE_trocken", type=str)
    parser.add_argument("Bruchdehnung_TPE_konditioniert", type=str)
    parser.add_argument("Bruchdehnung_Parallel_trocken", type=str)
    parser.add_argument("Bruchdehnung_Parallel_konditioniert", type=str)
    parser.add_argument("Bruchspannung_MPa_trocken", type=str)
    parser.add_argument("Bruchspannung_MPa_konditioniert", type=str)
    parser.add_argument("Bruchspannung_TPE_MPa_trocken", type=str)
    parser.add_argument("Bruchspannung_TPE_MPa_konditioniert", type=str)
    parser.add_argument("Bruchspannung_Parallel_MPa_trocken", type=str)
    parser.add_argument("Bruchspannung_Parallel_MPa_konditioniert", type=str)
    parser.add_argument("Bruchspannung_Senkrecht_MPa_trocken", type=str)
    parser.add_argument("Bruchspannung_Senkrecht_MPa_konditioniert", type=str)
    parser.add_argument("Zugmodul_MPa_trocken", type=str)
    parser.add_argument("Zugmodul_MPa_konditioniert", type=str)
    parser.add_argument("Zugmodul_Kriech_1h_MPa_trocken", type=str)
    parser.add_argument("Zugmodul_Kriech_1h_MPa_konditioniert", type=str)
    parser.add_argument("Zugmodul_Kriech_1000h_MPa_trocken", type=str)
    parser.add_argument("Zugmodul_Kriech_1000h_MPa_konditioniert", type=str)
    parser.add_argument("Zugmodul_Parallel_MPa_trocken", type=str)
    parser.add_argument("Zugmodul_Parallel_MPa_konditioniert", type=str)
    parser.add_argument("Zugmodul_Senkrecht_MPa_trocken", type=str)
    parser.add_argument("Zugmodul_Senkrecht_MPa_konditioniert", type=str)

    def get(self):
        args = self.parser.parse_args()
        print(args['id'])
        print(args['mat_desc'])
        print(args['mat_int_desc'])

        return [
            {
                "id": "1",
                "mat_desc": "ACRYMID\u00ae TT50",
                "mat_int_desc": None,
                "t_fam_id": 43.0,
                "campus_fam": "Techn-Sonst",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": "2020-07-29 12:52:12",
                "unit": "kg",
                "del_kz": 0,
                "producer": "Evonik Industries AG",
                "Verarbeitungsmethode": "Spritzgie\u00dfen",
                "dichte_trocken": 1210.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": 10.0,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": 260.0,
                "Temperatur_konditioniert": None,
                "MVR_trocken": 5.0,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": 3.0,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": 80.0,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": 4000.0,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "2",
                "mat_desc": "ACRYMID\u00ae TT70",
                "mat_int_desc": None,
                "t_fam_id": 43.0,
                "campus_fam": "Techn-Sonst",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "Evonik Industries AG",
                "Verarbeitungsmethode": "Spritzgie\u00dfen",
                "dichte_trocken": 1210.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": 10.0,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": 260.0,
                "Temperatur_konditioniert": None,
                "MVR_trocken": 1.7,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": 3.0,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": 80.0,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": 4000.0,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "3",
                "mat_desc": "Akulon\u00ae CO-KGV4 /A JN.00.86",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Spritzgie\u00dfen",
                "dichte_trocken": 1340.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": 3.0,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": 63.0,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": 4800.0,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "4",
                "mat_desc": "Akulon\u00ae CO-KGV5",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Spritzgie\u00dfen",
                "dichte_trocken": 1360.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": 2.5,
                "Bruchdehnung_konditioniert": 20.3,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": 85.0,
                "Bruchspannung_MPa_konditioniert": 37.0,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": 6000.0,
                "Zugmodul_MPa_konditioniert": 2810.0,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "5",
                "mat_desc": "Akulon\u00ae Diablo HDT2500 BK00001",
                "mat_int_desc": None,
                "t_fam_id": 40.0,
                "campus_fam": "PA66",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Spritzgie\u00dfen",
                "dichte_trocken": 1410.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": 43954.0,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": 190.0,
                "Bruchspannung_MPa_konditioniert": 110.0,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": 11000.0,
                "Zugmodul_MPa_konditioniert": 6500.0,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "6",
                "mat_desc": "Akulon\u00ae Diablo HT-HG0",
                "mat_int_desc": None,
                "t_fam_id": 105.0,
                "campus_fam": "PA66+PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Spritzgie\u00dfen",
                "dichte_trocken": 1580.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": 2.4,
                "Bruchdehnung_konditioniert": 4.6,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": 230.0,
                "Bruchspannung_MPa_konditioniert": 145.0,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": 17000.0,
                "Zugmodul_MPa_konditioniert": 10000.0,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "7",
                "mat_desc": "Akulon\u00ae Diablo HT-HG6",
                "mat_int_desc": None,
                "t_fam_id": 105.0,
                "campus_fam": "PA66+PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Spritzgie\u00dfen",
                "dichte_trocken": 1370.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": 3.1,
                "Bruchdehnung_konditioniert": 6.5,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": 185.0,
                "Bruchspannung_MPa_konditioniert": 95.0,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": 9800.0,
                "Zugmodul_MPa_konditioniert": 5500.0,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "8",
                "mat_desc": "Akulon\u00ae F-X9182",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Folienextrusion, \u00fcbrige Extrusion, Beschichten",
                "dichte_trocken": 1130.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": None,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": None,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": None,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "9",
                "mat_desc": "Akulon\u00ae F-X9190",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Spritzgie\u00dfen",
                "dichte_trocken": 1130.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": None,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": 20.0,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": None,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": 3200.0,
                "Zugmodul_MPa_konditioniert": 1000.0,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "10",
                "mat_desc": "Akulon\u00ae F-X9215",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Spritzgie\u00dfen",
                "dichte_trocken": 1130.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": None,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": None,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": 2000.0,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "11",
                "mat_desc": "Akulon\u00ae F127",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Folienextrusion, \u00fcbrige Extrusion, Gie\u00dfen",
                "dichte_trocken": 1130.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": None,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": None,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": None,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "12",
                "mat_desc": "Akulon\u00ae F128",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Folienextrusion, \u00fcbrige Extrusion, Gie\u00dfen",
                "dichte_trocken": 1130.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": None,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": None,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": None,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "13",
                "mat_desc": "Akulon\u00ae F130",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Folienextrusion, \u00fcbrige Extrusion, Gie\u00dfen",
                "dichte_trocken": 1130.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": None,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": None,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": None,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "14",
                "mat_desc": "Akulon\u00ae F130-C",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Folienextrusion, \u00fcbrige Extrusion, Gie\u00dfen",
                "dichte_trocken": 1130.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": None,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": None,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": None,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "15",
                "mat_desc": "Akulon\u00ae F130-C1",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Folienextrusion, \u00fcbrige Extrusion, Gie\u00dfen",
                "dichte_trocken": 1130.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": None,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": None,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": None,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "16",
                "mat_desc": "Akulon\u00ae F130-C2",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Folienextrusion, \u00fcbrige Extrusion, Gie\u00dfen",
                "dichte_trocken": 1130.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": None,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": None,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": None,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "17",
                "mat_desc": "Akulon\u00ae F130-C3",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Folienextrusion, \u00fcbrige Extrusion",
                "dichte_trocken": 1130.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": None,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": None,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": None,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "18",
                "mat_desc": "Akulon\u00ae F130-E5",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Folienextrusion, \u00fcbrige Extrusion, Gie\u00dfen",
                "dichte_trocken": 1130.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": None,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": None,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": None,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "19",
                "mat_desc": "Akulon\u00ae F132",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Folienextrusion, \u00fcbrige Extrusion, Gie\u00dfen",
                "dichte_trocken": 1130.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": None,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": None,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": None,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            },
            {
                "id": "20",
                "mat_desc": "Akulon\u00ae F132-C1",
                "mat_int_desc": None,
                "t_fam_id": 37.0,
                "campus_fam": "PA6",
                "t_mara_art_id": 1.0,
                "upload_kind": "DIMOP",
                "created_at": "2020-06-13 00:00:00",
                "updated_at": None,
                "unit": "kg",
                "del_kz": 0,
                "producer": "DSM Engineering Plastics",
                "Verarbeitungsmethode": "Folienextrusion, \u00fcbrige Extrusion, Gie\u00dfen",
                "dichte_trocken": 1130.0,
                "dichte_konditioniert": None,
                "Belastung_trocken": None,
                "Belastung_konditioniert": None,
                "Temperatur_trocken": None,
                "Temperatur_konditioniert": None,
                "MVR_trocken": None,
                "MVR_konditioniert": None,
                "Bruchdehnung_trocken": None,
                "Bruchdehnung_konditioniert": None,
                "Bruchdehnung_Nominell_trocken": None,
                "Bruchdehnung_Nominell_konditioniert": None,
                "Bruchdehnung_TPE_trocken": None,
                "Bruchdehnung_TPE_konditioniert": None,
                "Bruchdehnung_Parallel_trocken": None,
                "Bruchdehnung_Parallel_konditioniert": None,
                "Bruchspannung_MPa_trocken": None,
                "Bruchspannung_MPa_konditioniert": None,
                "Bruchspannung_TPE_MPa_trocken": None,
                "Bruchspannung_TPE_MPa_konditioniert": None,
                "Bruchspannung_Parallel_MPa_trocken": None,
                "Bruchspannung_Parallel_MPa_konditioniert": None,
                "Bruchspannung_Senkrecht_MPa_trocken": None,
                "Bruchspannung_Senkrecht_MPa_konditioniert": None,
                "Zugmodul_MPa_trocken": None,
                "Zugmodul_MPa_konditioniert": None,
                "Zugmodul_Kriech_1h_MPa_trocken": None,
                "Zugmodul_Kriech_1h_MPa_konditioniert": None,
                "Zugmodul_Kriech_1000h_MPa_trocken": None,
                "Zugmodul_Kriech_1000h_MPa_konditioniert": None,
                "Zugmodul_Parallel_MPa_trocken": None,
                "Zugmodul_Parallel_MPa_konditioniert": None,
                "Zugmodul_Senkrecht_MPa_trocken": None,
                "Zugmodul_Senkrecht_MPa_konditioniert": None
            }
        ]
